### ISSUE TITLE
multiple phonebook entries

### ISSUE THREAD

**Issue by tiimwoolf** [Netkum-AG/telsearch_integration#3]
When using the plugin in the "Lookup + contact save mode" the contacts are saved in the defined phone book. But as far as I can tell, there is no built-in check to see if this contact with name or number already exists. So when implementing the plugin in this mode and a caller calls the pbx multiple times, a new contact is always created, but it always has exactly the same content.

**Comment by PierreAnken** [comment]
Hello Tim,
Thank you for the report.
I recommend you to check if the PBX recognises the contact by checking if the first digits from the caller name is different then the + sign, with a "jump to if" to avoid to call the lookup.
I'm going to documents it properly when back to the office and implements a check.

**Comment by PierreAnken** [comment]
Documentation updated.
